//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOFR.WebAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SOFR
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        public Nullable<decimal> SOFR_Index { get; set; }
   
        public Nullable<decimal> C30DayAverage { get; set; }
        public Nullable<decimal> C90DayAverage { get; set; }
        public Nullable<decimal> C180DayAverage { get; set; }
    }
}
